import streamlit as st
import pickle
import numpy as np

# Page configuration
st.set_page_config(
    page_title="AI Text Detector",
    page_icon="🤖",
    layout="centered"
)

# Load saved model and vectorizer using pickle
@st.cache_resource
def load_assets():
    with open("ai.pkl", "rb") as f_model:
        model = pickle.load(f_model)
    with open("tf.pkl", "rb") as f_tf:
        vectorizer = pickle.load(f_tf)
    return model, vectorizer

try:
    model, vectorizer = load_assets()
    assets_loaded = True
except Exception as e:
    assets_loaded = False
    st.error(f"Error loading model files: {e}")

# UI Header
st.title("🤖 AI vs. Human Text Detector")
st.markdown("Enter any text below to determine whether it was written by a **Human** or generated by **AI**.")

# User Input Area
text_input = st.text_area("Text Input", height=220, placeholder="Paste your text here to analyze...")

if st.button("Analyze Text", type="primary"):
    if not assets_loaded:
        st.warning("Model files missing! Make sure 'ai.pkl' and 'tf.pkl' are placed in the repository root directory.")
    elif not text_input.strip():
        st.warning("Please enter some text before analyzing.")
    # Check if input is too short (random short inputs confuse TF-IDF vectorizers)
    elif len(text_input.strip().split()) < 5:
        st.info("ℹ️ Text is too short for reliable analysis. Please enter at least 5 words.")
    else:
        # Vectorize input text
        text_vec = vectorizer.transform([text_input])
        
        # Get class probabilities
        probabilities = model.predict_proba(text_vec)[0]
        ai_prob = probabilities[1]  # Index 1 = AI probability
        
        st.divider()
        st.subheader("Results")
        
        # THRESHOLD ADJUSTMENT:
        # Require 85%+ probability to flag as AI. 
        # Anything lower is classified as Human to eliminate false positives on casual text.
        if ai_prob >= 0.85:
            confidence = ai_prob * 100
            st.error(f"🚨 **AI-Generated Text** (Confidence: {confidence:.2f}%)")
            st.progress(float(ai_prob))
        else:
            human_prob = 1.0 - ai_prob
            confidence = human_prob * 100
            st.success(f"✅ **Human-Written Text** (Confidence: {confidence:.2f}%)")
            st.progress(float(human_prob))
