import streamlit as st
import pickle

# Page configuration
st.set_page_config(
    page_title="AI Text Detector",
    page_icon="🔍",
    layout="centered"
)

# Load trained pipeline
@st.cache_resource
def load_model():
    with open("aidetector.pkl", "rb") as f:
        model = pickle.load(f)
    return model

try:
    model = load_model()
except FileNotFoundError:
    st.error("⚠️ `aidetector.pkl` not found. Please ensure it is in the same directory as `app.py`.")
    st.stop()
except Exception as e:
    st.error(f"⚠️ Error loading model: {e}")
    st.info("💡 Ensure your local Python environment has `scikit-learn==1.3.2` installed.")
    st.stop()

# Header & Sidebar
st.title("🔍 AI vs. Human Text Detector")
st.markdown("Analyze text to determine whether it was generated by **AI** or written by a **Human**.")

with st.sidebar:
    st.header("⚙️ Model Details")
    st.info(
        "**Architecture:** TF-IDF + Stacking Ensemble (LR, Naive Bayes, SGD + XGBoost Meta-Learner)\n\n"
        "**Training Data:** RAID & HC3 Datasets (~139k samples)\n\n"
        "**Test Accuracy:** ~94.8%"
    )
    st.caption("💡 *Note: Input at least 20–30 words for reliable results.*")

# Text input area
user_input = st.text_area(
    "Enter text to analyze:",
    height=200,
    placeholder="Paste an article, essay, or paragraph here..."
)

# Analyze Button
if st.button("Detect Text Origin", type="primary"):
    text_cleaned = user_input.strip()
    word_count = len(text_cleaned.split())

    if not text_cleaned:
        st.warning("Please enter some text to analyze.")
    elif word_count < 15:
        st.warning(f"⚠️ Text is too short ({word_count} words). Please enter at least 15–20 words for reliable analysis.")
    else:
        with st.spinner("Analyzing text patterns..."):
            # Predict probabilities [Prob(Human), Prob(AI)]
            probabilities = model.predict_proba([text_cleaned])[0]
            human_prob = probabilities[0]
            ai_prob = probabilities[1]
            prediction = 1 if ai_prob >= 0.5 else 0

        st.divider()

        # Display Result Callout
        if prediction == 1:
            st.error(f"🤖 **Likely AI-Generated** (Confidence: {ai_prob * 100:.1f}%)")
        else:
            st.success(f"✍️ **Likely Human-Written** (Confidence: {human_prob * 100:.1f}%)")

        # Visual Metrics
        st.subheader("Probability Breakdown")
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Human Score", f"{human_prob * 100:.1f}%")
            st.progress(float(human_prob))
        with col2:
            st.metric("AI Score", f"{ai_prob * 100:.1f}%")
            st.progress(float(ai_prob))

        if word_count < 40:
            st.info("ℹ️ *Short input detected. Accuracy improves with longer passages.*")
