import streamlit as st
import pickle
import numpy as np

# Page configuration
st.set_page_config(
    page_title="AI Text Detector",
    page_icon="🤖",
    layout="centered"
)

# Load saved model and vectorizer using pickle
@st.cache_resource
def load_assets():
    with open("ai.pkl", "rb") as f_model:
        model = pickle.load(f_model)
    with open("tf.pkl", "rb") as f_tf:
        vectorizer = pickle.load(f_tf)
    return model, vectorizer

try:
    model, vectorizer = load_assets()
    assets_loaded = True
except Exception as e:
    assets_loaded = False
    st.error(f"Error loading model files: {e}")

# UI Header
st.title("🤖 AI vs. Human Text Detector")
st.markdown("Enter any text below to determine whether it was written by a **Human** or generated by **AI**.")

# User Input Area
text_input = st.text_area("Text Input", height=220, placeholder="Paste your text here to analyze...")

if st.button("Analyze Text", type="primary"):
    if not assets_loaded:
        st.warning("Model files missing! Make sure 'ai.pkl' and 'tf.pkl' are placed in the repository root directory.")
    elif not text_input.strip():
        st.warning("Please enter some text before analyzing.")
    else:
        words = text_input.strip().split()
        
        # Vectorize input text
        text_vec = vectorizer.transform([text_input])
        
        # Get count of known vocabulary terms present in user input
        known_words_count = text_vec.nnz
        
        # Calculate base probabilities from model
        probabilities = model.predict_proba(text_vec)[0]
        raw_ai_prob = probabilities[1]
        
        # Short text or out-of-vocabulary inputs produce false confidence in imbalanced models.
        # If input has fewer than 10 words or lacks learned TF-IDF n-grams, force human default.
        if len(words) < 10 or known_words_count < 3:
            final_pred = 0  # Human
            confidence = 85.00
        elif raw_ai_prob >= 0.9995:  # Require extreme certainty for longer text
            final_pred = 1  # AI
            confidence = raw_ai_prob * 100
        else:
            final_pred = 0  # Default to Human for ambiguous text
            confidence = (1.0 - raw_ai_prob) * 100
        
        st.divider()
        st.subheader("Results")
        
        if final_pred == 1:
            st.error(f"🚨 **AI-Generated Text** (Confidence: {confidence:.2f}%)")
            st.progress(float(confidence / 100))
        else:
            st.success(f"✅ **Human-Written Text** (Confidence: {confidence:.2f}%)")
            st.progress(float(confidence / 100))
